/**
 * Devnet E2E proof helper: fund check → setup (if needed) → print proof template.
 *
 *   pnpm --filter @workspace/solana run record-devnet-e2e
 *
 * Optional:
 *   BKSPC_FORCE_INIT=1     recreate mint when legacy multisig manifest
 *   BKSPC_WRITE_PROOF=1    write docs/phase-4-devnet-e2e-proof-RESULTS.md
 *   BKSPC_SKIP_SETUP=1     only print template from existing manifest
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { Connection, LAMPORTS_PER_SOL, PublicKey } from "@solana/web3.js";
import {
  ROOT,
  assertDevnetRpc,
  devnetRpc,
  loadDeployerKeypair,
} from "./lib/devnet-guards.js";

const PROGRAM_ID = "7whUULzUwYkDRZkpuKRS6dFRR4eWfzQaXnS3mz5FbVXs";
const MIN_SOL = 1.5;
const REPO_ROOT = join(ROOT, "..", "..", "..");
const PROOF_DOC = join(REPO_ROOT, "docs", "phase-4-devnet-e2e-proof-RESULTS.md");

interface BkspcManifest {
  cluster?: string;
  mint?: string;
  programId?: string;
  configInitialized?: boolean;
  mintAuthorityType?: string;
  mintAuthority?: string;
  initSignature?: string;
  initializeConfigSignature?: string;
  treasuryMultisig?: string;
  createdAt?: string;
}

function manifestPath(): string {
  return join(ROOT, "devnet", "bkspc-mint.json");
}

function loadManifest(): BkspcManifest | null {
  const path = manifestPath();
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8")) as BkspcManifest;
}

function needsSetup(manifest: BkspcManifest | null): boolean {
  if (!manifest) return true;
  if (manifest.cluster !== "devnet") return true;
  if (!manifest.configInitialized) return true;
  if (manifest.mintAuthorityType === "spl-multisig-2of2") return true;
  if (!manifest.programId || manifest.programId !== PROGRAM_ID) return true;
  return false;
}

async function checkBalance(rpc: string): Promise<number> {
  const deployer = loadDeployerKeypair();
  const connection = new Connection(rpc, "confirmed");
  const lamports = await connection.getBalance(deployer.publicKey);
  return lamports / LAMPORTS_PER_SOL;
}

function runSetup(): void {
  console.log("\nRunning setup-bkspc-devnet...\n");
  execSync("tsx scripts/setup-bkspc-devnet.ts", {
    cwd: ROOT,
    stdio: "inherit",
    env: process.env,
  });
}

function explorerTx(sig: string): string {
  return `https://explorer.solana.com/tx/${sig}?cluster=devnet`;
}

function buildProofMarkdown(manifest: BkspcManifest, deployer: PublicKey): string {
  const date = new Date().toISOString().slice(0, 10);
  const initSig = manifest.initializeConfigSignature ?? manifest.initSignature ?? "<pending>";
  const initExplorer =
    initSig !== "<pending>" ? explorerTx(initSig) : "<pending>";

  return `# Phase 4 Devnet E2E Proof — ${date}

> Auto-generated by \`record-devnet-e2e\`. Fill withdraw + burn sections after in-app demo.

## Setup
- Deployer: \`${deployer.toBase58()}\`
- Mint: \`${manifest.mint ?? "<pending>"}\`
- Program: \`${manifest.programId ?? PROGRAM_ID}\`
- Mint authority (PDA): \`${manifest.mintAuthority ?? "<pending>"}\`
- Treasury multisig: \`${manifest.treasuryMultisig ?? "<pending>"}\`
- configInitialized: \`${String(manifest.configInitialized ?? false)}\`
- initSignature: \`${manifest.initSignature ?? "<pending>"}\`
- initialize_config: \`${manifest.initializeConfigSignature ?? "<pending>"}\`
- Explorer (init/wire): ${initExplorer}
- Manifest: \`Code-Companion/artifacts/solana/devnet/bkspc-mint.json\`

## Tauri build (before withdraw/burn)
\`\`\`bash
export BKSPC_DEVNET_MANIFEST="$PWD/artifacts/solana/devnet/bkspc-mint.json"
cd Code-Companion/artifacts/blkspace
cargo build --manifest-path src-tauri/Cargo.toml --features bkspc-devnet
\`\`\`

## Withdraw (mint_rewards) — FILL AFTER DEMO
- Student handle: \`<handle>\`
- Student Solana pubkey: \`<pubkey>\`
- WB debited: \`<amount>\`
- Tx: \`<sig>\`
- Explorer: https://explorer.solana.com/tx/<sig>?cluster=devnet

## Burn (burn_tokens) — FILL AFTER DEMO
- Listing id: \`<id>\`
- Buyer Phantom: \`<pubkey>\`
- Burn amount (BKSPC): \`<amount>\`
- Tx: \`<sig>\`
- Explorer: https://explorer.solana.com/tx/<sig>?cluster=devnet

## settlement_status snapshot
\`\`\`json
<paste output from get_bkspc_settlement_status>
\`\`\`

## Checklist
- [ ] setup-bkspc-devnet complete (\`configInitialized: true\`)
- [ ] Tauri built with \`bkspc-devnet\`
- [ ] Live withdraw tx on devnet (not simulated)
- [ ] Live burn tx on devnet
- [ ] Seller WB credited; buyer owns NFT in app
`;
}

async function main(): Promise<void> {
  const rpc = devnetRpc();
  assertDevnetRpc(rpc);

  const deployer = loadDeployerKeypair();
  console.log("Phase 4 devnet E2E proof helper");
  console.log("  RPC:", rpc);
  console.log("  Deployer:", deployer.publicKey.toBase58());

  const balance = await checkBalance(rpc);
  console.log("  Balance:", balance.toFixed(4), "SOL");

  let manifest = loadManifest();
  const setupRequired = needsSetup(manifest);

  if (setupRequired && process.env.BKSPC_SKIP_SETUP !== "1") {
    if (balance < MIN_SOL) {
      console.error(
        `\nInsufficient devnet SOL (need ~${MIN_SOL}, have ${balance.toFixed(4)}).`,
      );
      console.error("  solana airdrop 2");
      console.error("  https://faucet.solana.com/");
      if (manifest?.mintAuthorityType === "spl-multisig-2of2") {
        console.error(
          "\nLegacy multisig manifest detected — when funded, run with BKSPC_FORCE_INIT=1",
        );
      }
      process.exit(1);
    }
    if (manifest?.mintAuthorityType === "spl-multisig-2of2" && process.env.BKSPC_FORCE_INIT !== "1") {
      console.error(
        "\nLegacy manifest (spl-multisig-2of2). Re-run with BKSPC_FORCE_INIT=1 to recreate mint + wire.",
      );
      process.exit(1);
    }
    runSetup();
    manifest = loadManifest();
  } else if (setupRequired) {
    console.warn("\nManifest not wired; BKSPC_SKIP_SETUP=1 — template may be incomplete.");
  } else {
    console.log("\nManifest already wired — skipping setup.");
  }

  if (!manifest) {
    throw new Error("bkspc-mint.json missing after setup");
  }

  const proof = buildProofMarkdown(manifest, deployer.publicKey);
  console.log("\n--- Proof template ---\n");
  console.log(proof);

  if (process.env.BKSPC_WRITE_PROOF === "1") {
    writeFileSync(PROOF_DOC, `${proof}\n`);
    console.log(`\nWrote ${PROOF_DOC}`);
  } else {
    console.log(
      `\nTo save: BKSPC_WRITE_PROOF=1 pnpm --filter @workspace/solana run record-devnet-e2e`,
    );
  }

  if (!manifest.configInitialized) {
    console.warn("\n⚠ configInitialized is false — complete wire before withdraw/burn demo.");
  } else {
    console.log("\nNext: build Tauri with bkspc-devnet, run withdraw + burn (see docs/phase-4-devnet-e2e-proof.md).");
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});