//! Auto-generated from src/lib/hbcu-catalog.ts — do not edit by hand.
//! Regenerate: python scripts/gen-hbcu-rust-seed.py

/// One HBCU institution for SQLite seed / directory.
#[derive(Debug, Clone, Copy)]
pub struct HbcuSeed {
  pub id: &'static str,
  pub school: &'static str,
  pub short_name: &'static str,
  pub city: &'static str,
  pub state: &'static str,
  pub founded: i32,
  pub control: &'static str, // public | private
  pub yard_label: &'static str,
}

/// Full catalog (103 institutions).
pub const HBCU_SEED: &[HbcuSeed] = &[
  HbcuSeed {
    id: "aamu",
    school: "Alabama A&M University",
    short_name: "AAMU",
    city: "Normal",
    state: "AL",
    founded: 1875,
    control: "public",
    yard_label: "AAMU Yard",
  },
  HbcuSeed {
    id: "asu",
    school: "Alabama State University",
    short_name: "ASU",
    city: "Montgomery",
    state: "AL",
    founded: 1867,
    control: "public",
    yard_label: "ASU Yard",
  },
  HbcuSeed {
    id: "albany-st",
    school: "Albany State University",
    short_name: "Albany State",
    city: "Albany",
    state: "GA",
    founded: 1903,
    control: "public",
    yard_label: "Albany State Yard",
  },
  HbcuSeed {
    id: "alcorn-st",
    school: "Alcorn State University",
    short_name: "Alcorn State",
    city: "Lorman",
    state: "MS",
    founded: 1871,
    control: "public",
    yard_label: "Alcorn State Yard",
  },
  HbcuSeed {
    id: "allen",
    school: "Allen University",
    short_name: "Allen",
    city: "Columbia",
    state: "SC",
    founded: 1870,
    control: "private",
    yard_label: "Allen Yard",
  },
  HbcuSeed {
    id: "american-baptist",
    school: "American Baptist College",
    short_name: "American Baptist",
    city: "Nashville",
    state: "TN",
    founded: 1924,
    control: "private",
    yard_label: "American Baptist Yard",
  },
  HbcuSeed {
    id: "u-arkansas-at-pine-bluff",
    school: "University of Arkansas at Pine Bluff",
    short_name: "UAPB",
    city: "Pine Bluff",
    state: "AR",
    founded: 1873,
    control: "public",
    yard_label: "UAPB Yard",
  },
  HbcuSeed {
    id: "arkansas-baptist",
    school: "Arkansas Baptist College",
    short_name: "Arkansas Baptist",
    city: "Little Rock",
    state: "AR",
    founded: 1884,
    control: "private",
    yard_label: "Arkansas Baptist Yard",
  },
  HbcuSeed {
    id: "barber-scotia",
    school: "Barber-Scotia College",
    short_name: "Barber-Scotia",
    city: "Concord",
    state: "NC",
    founded: 1867,
    control: "private",
    yard_label: "Barber-Scotia Yard",
  },
  HbcuSeed {
    id: "benedict",
    school: "Benedict College",
    short_name: "Benedict",
    city: "Columbia",
    state: "SC",
    founded: 1870,
    control: "private",
    yard_label: "Benedict Yard",
  },
  HbcuSeed {
    id: "bennett",
    school: "Bennett College",
    short_name: "Bennett",
    city: "Greensboro",
    state: "NC",
    founded: 1873,
    control: "private",
    yard_label: "Bennett Yard",
  },
  HbcuSeed {
    id: "bcu",
    school: "Bethune-Cookman University",
    short_name: "Bethune-Cookman",
    city: "Daytona Beach",
    state: "FL",
    founded: 1904,
    control: "private",
    yard_label: "Bethune-Cookman Yard",
  },
  HbcuSeed {
    id: "bishop-st-cc",
    school: "Bishop State Community College",
    short_name: "Bishop State Community",
    city: "Mobile",
    state: "AL",
    founded: 1927,
    control: "public",
    yard_label: "Bishop State Community Yard",
  },
  HbcuSeed {
    id: "bluefield-st",
    school: "Bluefield State University",
    short_name: "Bluefield State",
    city: "Bluefield",
    state: "WV",
    founded: 1895,
    control: "public",
    yard_label: "Bluefield State Yard",
  },
  HbcuSeed {
    id: "bowie",
    school: "Bowie State University",
    short_name: "Bowie State",
    city: "Bowie",
    state: "MD",
    founded: 1865,
    control: "public",
    yard_label: "Bowie State Yard",
  },
  HbcuSeed {
    id: "central-st",
    school: "Central State University",
    short_name: "Central State",
    city: "Wilberforce",
    state: "OH",
    founded: 1887,
    control: "public",
    yard_label: "Central State Yard",
  },
  HbcuSeed {
    id: "cheyney-u-pennsylvania",
    school: "Cheyney University of Pennsylvania",
    short_name: "Cheyney",
    city: "Cheyney",
    state: "PA",
    founded: 1837,
    control: "public",
    yard_label: "Cheyney Yard",
  },
  HbcuSeed {
    id: "claflin",
    school: "Claflin University",
    short_name: "Claflin",
    city: "Orangeburg",
    state: "SC",
    founded: 1869,
    control: "private",
    yard_label: "Claflin Yard",
  },
  HbcuSeed {
    id: "cau",
    school: "Clark Atlanta University",
    short_name: "Clark Atlanta",
    city: "Atlanta",
    state: "GA",
    founded: 1865,
    control: "private",
    yard_label: "Clark Atlanta Yard",
  },
  HbcuSeed {
    id: "clinton",
    school: "Clinton College",
    short_name: "Clinton",
    city: "Rock Hill",
    state: "SC",
    founded: 1894,
    control: "private",
    yard_label: "Clinton Yard",
  },
  HbcuSeed {
    id: "coahoma-cc",
    school: "Coahoma Community College",
    short_name: "Coahoma Community",
    city: "Clarksdale",
    state: "MS",
    founded: 1924,
    control: "public",
    yard_label: "Coahoma Community Yard",
  },
  HbcuSeed {
    id: "coppin-st",
    school: "Coppin State University",
    short_name: "Coppin State",
    city: "Baltimore",
    state: "MD",
    founded: 1900,
    control: "public",
    yard_label: "Coppin State Yard",
  },
  HbcuSeed {
    id: "dsu",
    school: "Delaware State University",
    short_name: "Delaware State",
    city: "Dover",
    state: "DE",
    founded: 1891,
    control: "public",
    yard_label: "Delaware State Yard",
  },
  HbcuSeed {
    id: "denmark-tech",
    school: "Denmark Technical College",
    short_name: "Denmark Technical",
    city: "Denmark",
    state: "SC",
    founded: 1947,
    control: "public",
    yard_label: "Denmark Technical Yard",
  },
  HbcuSeed {
    id: "dillard",
    school: "Dillard University",
    short_name: "Dillard",
    city: "New Orleans",
    state: "LA",
    founded: 1869,
    control: "private",
    yard_label: "Dillard Yard",
  },
  HbcuSeed {
    id: "u-district-of-columbia",
    school: "University of the District of Columbia",
    short_name: "UDC",
    city: "Washington",
    state: "DC",
    founded: 1851,
    control: "public",
    yard_label: "UDC Yard",
  },
  HbcuSeed {
    id: "edward-waters",
    school: "Edward Waters University",
    short_name: "Edward Waters",
    city: "Jacksonville",
    state: "FL",
    founded: 1866,
    control: "private",
    yard_label: "Edward Waters Yard",
  },
  HbcuSeed {
    id: "elizabeth-city-st",
    school: "Elizabeth City State University",
    short_name: "Elizabeth City State",
    city: "Elizabeth City",
    state: "NC",
    founded: 1891,
    control: "public",
    yard_label: "Elizabeth City State Yard",
  },
  HbcuSeed {
    id: "fayetteville-st",
    school: "Fayetteville State University",
    short_name: "Fayetteville State",
    city: "Fayetteville",
    state: "NC",
    founded: 1867,
    control: "public",
    yard_label: "Fayetteville State Yard",
  },
  HbcuSeed {
    id: "fisk",
    school: "Fisk University",
    short_name: "Fisk",
    city: "Nashville",
    state: "TN",
    founded: 1866,
    control: "private",
    yard_label: "Fisk Yard",
  },
  HbcuSeed {
    id: "famu",
    school: "Florida A&M University",
    short_name: "FAMU",
    city: "Tallahassee",
    state: "FL",
    founded: 1887,
    control: "public",
    yard_label: "FAMU Yard",
  },
  HbcuSeed {
    id: "florida-memorial",
    school: "Florida Memorial University",
    short_name: "Florida Memorial",
    city: "Miami Gardens",
    state: "FL",
    founded: 1879,
    control: "private",
    yard_label: "Florida Memorial Yard",
  },
  HbcuSeed {
    id: "fort-valley-st",
    school: "Fort Valley State University",
    short_name: "Fort Valley State",
    city: "Fort Valley",
    state: "GA",
    founded: 1895,
    control: "public",
    yard_label: "Fort Valley State Yard",
  },
  HbcuSeed {
    id: "gadsden-st-cc",
    school: "Gadsden State Community College",
    short_name: "Gadsden State Community",
    city: "Gadsden",
    state: "AL",
    founded: 1925,
    control: "public",
    yard_label: "Gadsden State Community Yard",
  },
  HbcuSeed {
    id: "grambling",
    school: "Grambling State University",
    short_name: "Grambling State",
    city: "Grambling",
    state: "LA",
    founded: 1901,
    control: "public",
    yard_label: "Grambling State Yard",
  },
  HbcuSeed {
    id: "hampton",
    school: "Hampton University",
    short_name: "Hampton",
    city: "Hampton",
    state: "VA",
    founded: 1868,
    control: "private",
    yard_label: "Hampton Yard",
  },
  HbcuSeed {
    id: "harris-stowe-st",
    school: "Harris-Stowe State University",
    short_name: "Harris-Stowe",
    city: "St. Louis",
    state: "MO",
    founded: 1857,
    control: "public",
    yard_label: "Harris-Stowe Yard",
  },
  HbcuSeed {
    id: "hinds-cc-at-utica",
    school: "Hinds Community College at Utica",
    short_name: "Hinds Utica",
    city: "Utica",
    state: "MS",
    founded: 1903,
    control: "public",
    yard_label: "Hinds Utica Yard",
  },
  HbcuSeed {
    id: "howard",
    school: "Howard University",
    short_name: "Howard",
    city: "Washington",
    state: "DC",
    founded: 1867,
    control: "private",
    yard_label: "Howard Yard",
  },
  HbcuSeed {
    id: "huston-tillotson",
    school: "Huston-Tillotson University",
    short_name: "Huston-Tillotson",
    city: "Austin",
    state: "TX",
    founded: 1875,
    control: "private",
    yard_label: "Huston-Tillotson Yard",
  },
  HbcuSeed {
    id: "interdenominational-theological-",
    school: "Interdenominational Theological Center",
    short_name: "ITC",
    city: "Atlanta",
    state: "GA",
    founded: 1958,
    control: "private",
    yard_label: "ITC Yard",
  },
  HbcuSeed {
    id: "j-f-drake-st-ctc",
    school: "J. F. Drake State Community and Technical College",
    short_name: "Drake State",
    city: "Huntsville",
    state: "AL",
    founded: 1961,
    control: "public",
    yard_label: "Drake State Yard",
  },
  HbcuSeed {
    id: "jsu",
    school: "Jackson State University",
    short_name: "JSU",
    city: "Jackson",
    state: "MS",
    founded: 1877,
    control: "public",
    yard_label: "JSU Yard",
  },
  HbcuSeed {
    id: "jarvis-christian",
    school: "Jarvis Christian University",
    short_name: "Jarvis Christian",
    city: "Hawkins",
    state: "TX",
    founded: 1912,
    control: "private",
    yard_label: "Jarvis Christian Yard",
  },
  HbcuSeed {
    id: "johnson-c-smith",
    school: "Johnson C. Smith University",
    short_name: "Johnson C. Smith",
    city: "Charlotte",
    state: "NC",
    founded: 1867,
    control: "private",
    yard_label: "Johnson C. Smith Yard",
  },
  HbcuSeed {
    id: "kentucky-st",
    school: "Kentucky State University",
    short_name: "Kentucky State",
    city: "Frankfort",
    state: "KY",
    founded: 1886,
    control: "public",
    yard_label: "Kentucky State Yard",
  },
  HbcuSeed {
    id: "knoxville",
    school: "Knoxville College",
    short_name: "Knoxville",
    city: "Knoxville",
    state: "TN",
    founded: 1875,
    control: "private",
    yard_label: "Knoxville Yard",
  },
  HbcuSeed {
    id: "lane",
    school: "Lane College",
    short_name: "Lane",
    city: "Jackson",
    state: "TN",
    founded: 1882,
    control: "private",
    yard_label: "Lane Yard",
  },
  HbcuSeed {
    id: "langston",
    school: "Langston University",
    short_name: "Langston",
    city: "Langston",
    state: "OK",
    founded: 1897,
    control: "public",
    yard_label: "Langston Yard",
  },
  HbcuSeed {
    id: "lawson-st-cc",
    school: "Lawson State Community College",
    short_name: "Lawson State Community",
    city: "Birmingham",
    state: "AL",
    founded: 1949,
    control: "public",
    yard_label: "Lawson State Community Yard",
  },
  HbcuSeed {
    id: "lemoyne-owen",
    school: "LeMoyne-Owen College",
    short_name: "LeMoyne-Owen",
    city: "Memphis",
    state: "TN",
    founded: 1862,
    control: "private",
    yard_label: "LeMoyne-Owen Yard",
  },
  HbcuSeed {
    id: "lincoln-u-missouri",
    school: "Lincoln University of Missouri",
    short_name: "Lincoln MO",
    city: "Jefferson City",
    state: "MO",
    founded: 1866,
    control: "public",
    yard_label: "Lincoln MO Yard",
  },
  HbcuSeed {
    id: "lincoln-u-pennsylvania",
    school: "Lincoln University of Pennsylvania",
    short_name: "Lincoln PA",
    city: "Lincoln University",
    state: "PA",
    founded: 1854,
    control: "public",
    yard_label: "Lincoln PA Yard",
  },
  HbcuSeed {
    id: "livingstone",
    school: "Livingstone College",
    short_name: "Livingstone",
    city: "Salisbury",
    state: "NC",
    founded: 1879,
    control: "private",
    yard_label: "Livingstone Yard",
  },
  HbcuSeed {
    id: "u-maryland-eastern-shore",
    school: "University of Maryland Eastern Shore",
    short_name: "UMES",
    city: "Princess Anne",
    state: "MD",
    founded: 1886,
    control: "public",
    yard_label: "UMES Yard",
  },
  HbcuSeed {
    id: "meharry",
    school: "Meharry Medical College",
    short_name: "Meharry Medical",
    city: "Nashville",
    state: "TN",
    founded: 1876,
    control: "private",
    yard_label: "Meharry Medical Yard",
  },
  HbcuSeed {
    id: "miles",
    school: "Miles College",
    short_name: "Miles",
    city: "Fairfield",
    state: "AL",
    founded: 1898,
    control: "private",
    yard_label: "Miles Yard",
  },
  HbcuSeed {
    id: "mississippi-valley-st",
    school: "Mississippi Valley State University",
    short_name: "Mississippi Valley State",
    city: "Itta Bena",
    state: "MS",
    founded: 1950,
    control: "public",
    yard_label: "Mississippi Valley State Yard",
  },
  HbcuSeed {
    id: "morehouse",
    school: "Morehouse College",
    short_name: "Morehouse",
    city: "Atlanta",
    state: "GA",
    founded: 1867,
    control: "private",
    yard_label: "Morehouse Yard",
  },
  HbcuSeed {
    id: "morehouse-school-of-medicine",
    school: "Morehouse School of Medicine",
    short_name: "MSM",
    city: "Atlanta",
    state: "GA",
    founded: 1975,
    control: "private",
    yard_label: "MSM Yard",
  },
  HbcuSeed {
    id: "morgan",
    school: "Morgan State University",
    short_name: "Morgan State",
    city: "Baltimore",
    state: "MD",
    founded: 1867,
    control: "public",
    yard_label: "Morgan State Yard",
  },
  HbcuSeed {
    id: "morris-brown",
    school: "Morris Brown College",
    short_name: "Morris Brown",
    city: "Atlanta",
    state: "GA",
    founded: 1881,
    control: "private",
    yard_label: "Morris Brown Yard",
  },
  HbcuSeed {
    id: "morris",
    school: "Morris College",
    short_name: "Morris",
    city: "Sumter",
    state: "SC",
    founded: 1908,
    control: "private",
    yard_label: "Morris Yard",
  },
  HbcuSeed {
    id: "nsu",
    school: "Norfolk State University",
    short_name: "Norfolk State",
    city: "Norfolk",
    state: "VA",
    founded: 1935,
    control: "public",
    yard_label: "Norfolk State Yard",
  },
  HbcuSeed {
    id: "ncat",
    school: "North Carolina A&T State University",
    short_name: "NC A&T",
    city: "Greensboro",
    state: "NC",
    founded: 1891,
    control: "public",
    yard_label: "NC A&T Yard",
  },
  HbcuSeed {
    id: "north-carolina-central",
    school: "North Carolina Central University",
    short_name: "North Carolina Central",
    city: "Durham",
    state: "NC",
    founded: 1910,
    control: "public",
    yard_label: "North Carolina Central Yard",
  },
  HbcuSeed {
    id: "oakwood",
    school: "Oakwood University",
    short_name: "Oakwood",
    city: "Huntsville",
    state: "AL",
    founded: 1896,
    control: "private",
    yard_label: "Oakwood Yard",
  },
  HbcuSeed {
    id: "paine",
    school: "Paine College",
    short_name: "Paine",
    city: "Augusta",
    state: "GA",
    founded: 1882,
    control: "private",
    yard_label: "Paine Yard",
  },
  HbcuSeed {
    id: "paul-quinn",
    school: "Paul Quinn College",
    short_name: "Paul Quinn",
    city: "Dallas",
    state: "TX",
    founded: 1872,
    control: "private",
    yard_label: "Paul Quinn Yard",
  },
  HbcuSeed {
    id: "payne-theological-seminary",
    school: "Payne Theological Seminary",
    short_name: "Payne Theological",
    city: "Wilberforce",
    state: "OH",
    founded: 1856,
    control: "private",
    yard_label: "Payne Theological Yard",
  },
  HbcuSeed {
    id: "philander-smith",
    school: "Philander Smith University",
    short_name: "Philander Smith",
    city: "Little Rock",
    state: "AR",
    founded: 1877,
    control: "private",
    yard_label: "Philander Smith Yard",
  },
  HbcuSeed {
    id: "pvamu",
    school: "Prairie View A&M University",
    short_name: "PVAMU",
    city: "Prairie View",
    state: "TX",
    founded: 1876,
    control: "public",
    yard_label: "PVAMU Yard",
  },
  HbcuSeed {
    id: "rust",
    school: "Rust College",
    short_name: "Rust",
    city: "Holly Springs",
    state: "MS",
    founded: 1866,
    control: "private",
    yard_label: "Rust Yard",
  },
  HbcuSeed {
    id: "savannah-st",
    school: "Savannah State University",
    short_name: "Savannah State",
    city: "Savannah",
    state: "GA",
    founded: 1890,
    control: "public",
    yard_label: "Savannah State Yard",
  },
  HbcuSeed {
    id: "selma",
    school: "Selma University",
    short_name: "Selma",
    city: "Selma",
    state: "AL",
    founded: 1878,
    control: "private",
    yard_label: "Selma Yard",
  },
  HbcuSeed {
    id: "shaw",
    school: "Shaw University",
    short_name: "Shaw",
    city: "Raleigh",
    state: "NC",
    founded: 1865,
    control: "private",
    yard_label: "Shaw Yard",
  },
  HbcuSeed {
    id: "shelton-st-cc",
    school: "Shelton State Community College",
    short_name: "Shelton State Community",
    city: "Tuscaloosa",
    state: "AL",
    founded: 1952,
    control: "public",
    yard_label: "Shelton State Community Yard",
  },
  HbcuSeed {
    id: "simmons-of-kentucky",
    school: "Simmons College of Kentucky",
    short_name: "Simmons KY",
    city: "Louisville",
    state: "KY",
    founded: 1869,
    control: "private",
    yard_label: "Simmons KY Yard",
  },
  HbcuSeed {
    id: "south-carolina-st",
    school: "South Carolina State University",
    short_name: "South Carolina State",
    city: "Orangeburg",
    state: "SC",
    founded: 1896,
    control: "public",
    yard_label: "South Carolina State Yard",
  },
  HbcuSeed {
    id: "southern-at-new-orleans",
    school: "Southern University at New Orleans",
    short_name: "SUNO",
    city: "New Orleans",
    state: "LA",
    founded: 1956,
    control: "public",
    yard_label: "SUNO Yard",
  },
  HbcuSeed {
    id: "southern-at-shreveport",
    school: "Southern University at Shreveport",
    short_name: "SUSLA",
    city: "Shreveport",
    state: "LA",
    founded: 1967,
    control: "public",
    yard_label: "SUSLA Yard",
  },
  HbcuSeed {
    id: "southern",
    school: "Southern University and A&M College",
    short_name: "Southern U",
    city: "Baton Rouge",
    state: "LA",
    founded: 1880,
    control: "public",
    yard_label: "Southern U Yard",
  },
  HbcuSeed {
    id: "southwestern-christian",
    school: "Southwestern Christian College",
    short_name: "Southwestern Christian",
    city: "Terrell",
    state: "TX",
    founded: 1948,
    control: "private",
    yard_label: "Southwestern Christian Yard",
  },
  HbcuSeed {
    id: "spelman",
    school: "Spelman College",
    short_name: "Spelman",
    city: "Atlanta",
    state: "GA",
    founded: 1881,
    control: "private",
    yard_label: "Spelman Yard",
  },
  HbcuSeed {
    id: "st-augustine-s",
    school: "St. Augustine's University",
    short_name: "St. Aug's",
    city: "Raleigh",
    state: "NC",
    founded: 1867,
    control: "private",
    yard_label: "St. Aug's Yard",
  },
  HbcuSeed {
    id: "stillman",
    school: "Stillman College",
    short_name: "Stillman",
    city: "Tuscaloosa",
    state: "AL",
    founded: 1876,
    control: "private",
    yard_label: "Stillman Yard",
  },
  HbcuSeed {
    id: "talladega",
    school: "Talladega College",
    short_name: "Talladega",
    city: "Talladega",
    state: "AL",
    founded: 1867,
    control: "private",
    yard_label: "Talladega Yard",
  },
  HbcuSeed {
    id: "tsu",
    school: "Tennessee State University",
    short_name: "TSU",
    city: "Nashville",
    state: "TN",
    founded: 1912,
    control: "public",
    yard_label: "TSU Yard",
  },
  HbcuSeed {
    id: "texas",
    school: "Texas College",
    short_name: "Texas",
    city: "Tyler",
    state: "TX",
    founded: 1894,
    control: "private",
    yard_label: "Texas Yard",
  },
  HbcuSeed {
    id: "txsu",
    school: "Texas Southern University",
    short_name: "TSU Houston",
    city: "Houston",
    state: "TX",
    founded: 1927,
    control: "public",
    yard_label: "TSU Houston Yard",
  },
  HbcuSeed {
    id: "tougaloo",
    school: "Tougaloo College",
    short_name: "Tougaloo",
    city: "Tougaloo",
    state: "MS",
    founded: 1869,
    control: "private",
    yard_label: "Tougaloo Yard",
  },
  HbcuSeed {
    id: "trenholm-st-cc",
    school: "Trenholm State Community College",
    short_name: "Trenholm State Community",
    city: "Montgomery",
    state: "AL",
    founded: 1947,
    control: "public",
    yard_label: "Trenholm State Community Yard",
  },
  HbcuSeed {
    id: "tuskegee",
    school: "Tuskegee University",
    short_name: "Tuskegee",
    city: "Tuskegee",
    state: "AL",
    founded: 1881,
    control: "private",
    yard_label: "Tuskegee Yard",
  },
  HbcuSeed {
    id: "u-virgin-islands",
    school: "University of the Virgin Islands",
    short_name: "UVI",
    city: "St. Thomas",
    state: "VI",
    founded: 1962,
    control: "public",
    yard_label: "UVI Yard",
  },
  HbcuSeed {
    id: "vsu",
    school: "Virginia State University",
    short_name: "Virginia State",
    city: "Petersburg",
    state: "VA",
    founded: 1882,
    control: "public",
    yard_label: "Virginia State Yard",
  },
  HbcuSeed {
    id: "virginia-union",
    school: "Virginia Union University",
    short_name: "Virginia Union",
    city: "Richmond",
    state: "VA",
    founded: 1865,
    control: "private",
    yard_label: "Virginia Union Yard",
  },
  HbcuSeed {
    id: "virginia-u-lynchburg",
    school: "Virginia University of Lynchburg",
    short_name: "VU Lynchburg",
    city: "Lynchburg",
    state: "VA",
    founded: 1886,
    control: "private",
    yard_label: "VU Lynchburg Yard",
  },
  HbcuSeed {
    id: "voorhees",
    school: "Voorhees University",
    short_name: "Voorhees",
    city: "Denmark",
    state: "SC",
    founded: 1897,
    control: "private",
    yard_label: "Voorhees Yard",
  },
  HbcuSeed {
    id: "west-virginia-st",
    school: "West Virginia State University",
    short_name: "West Virginia State",
    city: "Institute",
    state: "WV",
    founded: 1891,
    control: "public",
    yard_label: "West Virginia State Yard",
  },
  HbcuSeed {
    id: "wilberforce",
    school: "Wilberforce University",
    short_name: "Wilberforce",
    city: "Wilberforce",
    state: "OH",
    founded: 1856,
    control: "private",
    yard_label: "Wilberforce Yard",
  },
  HbcuSeed {
    id: "wiley",
    school: "Wiley University",
    short_name: "Wiley",
    city: "Marshall",
    state: "TX",
    founded: 1873,
    control: "private",
    yard_label: "Wiley Yard",
  },
  HbcuSeed {
    id: "winston-salem-st",
    school: "Winston-Salem State University",
    short_name: "Winston-Salem State",
    city: "Winston-Salem",
    state: "NC",
    founded: 1892,
    control: "public",
    yard_label: "Winston-Salem State Yard",
  },
  HbcuSeed {
    id: "xavier",
    school: "Xavier University of Louisiana",
    short_name: "Xavier LA",
    city: "New Orleans",
    state: "LA",
    founded: 1915,
    control: "private",
    yard_label: "Xavier LA Yard",
  },
];

pub fn hbcu_seed_count() -> usize {
  HBCU_SEED.len()
}

