[package]
name = "bkspc"
version = "0.1.0"
description = "BKSPC settlement — Token-2022 convert + legacy SPL mint/burn"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bkspc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = { version = "0.29.0", features = ["token", "token_2022"] }