/**
 * Yard catalog — every campus sits at the same table.
 * HBCU list (DOE/NCES) plus NCAA/SEC crossover yards. Not HBCU-only.
 */

export type HbcuControl = "public" | "private";
export type YardKind = "hbcu" | "ncaa";

export interface HbcuInstitution {
  id: string;
  school: string;
  shortName: string;
  city: string;
  state: string;
  founded: number;
  control: HbcuControl;
  /** Short yard label shown in UI */
  yardLabel: string;
  /** Default hbcu when omitted (legacy generated rows). */
  kind?: YardKind;
  /** Optional conference / league label (SEC, MVC, …). */
  conference?: string;
}

/** Featured yards with richer skins (gradients in yard-themes). */
export const FEATURED_YARD_IDS = [
  "tsu",
  "howard",
  "spelman",
  "famu",
  "morehouse",
  "meharry",
  "ncat",
  "hampton",
  "tuskegee",
  "jsu",
  "grambling",
  "pvamu",
  "vanderbilt",
  "belmont",
  "tennessee",
  "ut-austin",
] as const;

export type FeaturedYardId = (typeof FEATURED_YARD_IDS)[number];

/** Type-safe membership check (avoids `includes` narrowing on `as const` tuples). */
export function isFeaturedYardId(id: string): id is FeaturedYardId {
  return (FEATURED_YARD_IDS as readonly string[]).includes(id);
}

export const HBCU_CATALOG: HbcuInstitution[] = [
  {
    id: "aamu",
    school: "Alabama A&M University",
    shortName: "AAMU",
    city: "Normal",
    state: "AL",
    founded: 1875,
    control: "public",
    yardLabel: "AAMU Yard",
  },
  {
    id: "asu",
    school: "Alabama State University",
    shortName: "ASU",
    city: "Montgomery",
    state: "AL",
    founded: 1867,
    control: "public",
    yardLabel: "ASU Yard",
  },
  {
    id: "albany-st",
    school: "Albany State University",
    shortName: "Albany State",
    city: "Albany",
    state: "GA",
    founded: 1903,
    control: "public",
    yardLabel: "Albany State Yard",
  },
  {
    id: "alcorn-st",
    school: "Alcorn State University",
    shortName: "Alcorn State",
    city: "Lorman",
    state: "MS",
    founded: 1871,
    control: "public",
    yardLabel: "Alcorn State Yard",
  },
  {
    id: "allen",
    school: "Allen University",
    shortName: "Allen",
    city: "Columbia",
    state: "SC",
    founded: 1870,
    control: "private",
    yardLabel: "Allen Yard",
  },
  {
    id: "american-baptist",
    school: "American Baptist College",
    shortName: "American Baptist",
    city: "Nashville",
    state: "TN",
    founded: 1924,
    control: "private",
    yardLabel: "American Baptist Yard",
  },
  {
    id: "u-arkansas-at-pine-bluff",
    school: "University of Arkansas at Pine Bluff",
    shortName: "UAPB",
    city: "Pine Bluff",
    state: "AR",
    founded: 1873,
    control: "public",
    yardLabel: "UAPB Yard",
  },
  {
    id: "arkansas-baptist",
    school: "Arkansas Baptist College",
    shortName: "Arkansas Baptist",
    city: "Little Rock",
    state: "AR",
    founded: 1884,
    control: "private",
    yardLabel: "Arkansas Baptist Yard",
  },
  {
    id: "barber-scotia",
    school: "Barber-Scotia College",
    shortName: "Barber-Scotia",
    city: "Concord",
    state: "NC",
    founded: 1867,
    control: "private",
    yardLabel: "Barber-Scotia Yard",
  },
  {
    id: "benedict",
    school: "Benedict College",
    shortName: "Benedict",
    city: "Columbia",
    state: "SC",
    founded: 1870,
    control: "private",
    yardLabel: "Benedict Yard",
  },
  {
    id: "bennett",
    school: "Bennett College",
    shortName: "Bennett",
    city: "Greensboro",
    state: "NC",
    founded: 1873,
    control: "private",
    yardLabel: "Bennett Yard",
  },
  {
    id: "bcu",
    school: "Bethune-Cookman University",
    shortName: "Bethune-Cookman",
    city: "Daytona Beach",
    state: "FL",
    founded: 1904,
    control: "private",
    yardLabel: "Bethune-Cookman Yard",
  },
  {
    id: "bishop-st-cc",
    school: "Bishop State Community College",
    shortName: "Bishop State Community",
    city: "Mobile",
    state: "AL",
    founded: 1927,
    control: "public",
    yardLabel: "Bishop State Community Yard",
  },
  {
    id: "bluefield-st",
    school: "Bluefield State University",
    shortName: "Bluefield State",
    city: "Bluefield",
    state: "WV",
    founded: 1895,
    control: "public",
    yardLabel: "Bluefield State Yard",
  },
  {
    id: "bowie",
    school: "Bowie State University",
    shortName: "Bowie State",
    city: "Bowie",
    state: "MD",
    founded: 1865,
    control: "public",
    yardLabel: "Bowie State Yard",
  },
  {
    id: "central-st",
    school: "Central State University",
    shortName: "Central State",
    city: "Wilberforce",
    state: "OH",
    founded: 1887,
    control: "public",
    yardLabel: "Central State Yard",
  },
  {
    id: "cheyney-u-pennsylvania",
    school: "Cheyney University of Pennsylvania",
    shortName: "Cheyney",
    city: "Cheyney",
    state: "PA",
    founded: 1837,
    control: "public",
    yardLabel: "Cheyney Yard",
  },
  {
    id: "claflin",
    school: "Claflin University",
    shortName: "Claflin",
    city: "Orangeburg",
    state: "SC",
    founded: 1869,
    control: "private",
    yardLabel: "Claflin Yard",
  },
  {
    id: "cau",
    school: "Clark Atlanta University",
    shortName: "Clark Atlanta",
    city: "Atlanta",
    state: "GA",
    founded: 1865,
    control: "private",
    yardLabel: "Clark Atlanta Yard",
  },
  {
    id: "clinton",
    school: "Clinton College",
    shortName: "Clinton",
    city: "Rock Hill",
    state: "SC",
    founded: 1894,
    control: "private",
    yardLabel: "Clinton Yard",
  },
  {
    id: "coahoma-cc",
    school: "Coahoma Community College",
    shortName: "Coahoma Community",
    city: "Clarksdale",
    state: "MS",
    founded: 1924,
    control: "public",
    yardLabel: "Coahoma Community Yard",
  },
  {
    id: "coppin-st",
    school: "Coppin State University",
    shortName: "Coppin State",
    city: "Baltimore",
    state: "MD",
    founded: 1900,
    control: "public",
    yardLabel: "Coppin State Yard",
  },
  {
    id: "dsu",
    school: "Delaware State University",
    shortName: "Delaware State",
    city: "Dover",
    state: "DE",
    founded: 1891,
    control: "public",
    yardLabel: "Delaware State Yard",
  },
  {
    id: "denmark-tech",
    school: "Denmark Technical College",
    shortName: "Denmark Technical",
    city: "Denmark",
    state: "SC",
    founded: 1947,
    control: "public",
    yardLabel: "Denmark Technical Yard",
  },
  {
    id: "dillard",
    school: "Dillard University",
    shortName: "Dillard",
    city: "New Orleans",
    state: "LA",
    founded: 1869,
    control: "private",
    yardLabel: "Dillard Yard",
  },
  {
    id: "u-district-of-columbia",
    school: "University of the District of Columbia",
    shortName: "UDC",
    city: "Washington",
    state: "DC",
    founded: 1851,
    control: "public",
    yardLabel: "UDC Yard",
  },
  {
    id: "edward-waters",
    school: "Edward Waters University",
    shortName: "Edward Waters",
    city: "Jacksonville",
    state: "FL",
    founded: 1866,
    control: "private",
    yardLabel: "Edward Waters Yard",
  },
  {
    id: "elizabeth-city-st",
    school: "Elizabeth City State University",
    shortName: "Elizabeth City State",
    city: "Elizabeth City",
    state: "NC",
    founded: 1891,
    control: "public",
    yardLabel: "Elizabeth City State Yard",
  },
  {
    id: "fayetteville-st",
    school: "Fayetteville State University",
    shortName: "Fayetteville State",
    city: "Fayetteville",
    state: "NC",
    founded: 1867,
    control: "public",
    yardLabel: "Fayetteville State Yard",
  },
  {
    id: "fisk",
    school: "Fisk University",
    shortName: "Fisk",
    city: "Nashville",
    state: "TN",
    founded: 1866,
    control: "private",
    yardLabel: "Fisk Yard",
  },
  {
    id: "famu",
    school: "Florida A&M University",
    shortName: "FAMU",
    city: "Tallahassee",
    state: "FL",
    founded: 1887,
    control: "public",
    yardLabel: "FAMU Yard",
  },
  {
    id: "florida-memorial",
    school: "Florida Memorial University",
    shortName: "Florida Memorial",
    city: "Miami Gardens",
    state: "FL",
    founded: 1879,
    control: "private",
    yardLabel: "Florida Memorial Yard",
  },
  {
    id: "fort-valley-st",
    school: "Fort Valley State University",
    shortName: "Fort Valley State",
    city: "Fort Valley",
    state: "GA",
    founded: 1895,
    control: "public",
    yardLabel: "Fort Valley State Yard",
  },
  {
    id: "gadsden-st-cc",
    school: "Gadsden State Community College",
    shortName: "Gadsden State Community",
    city: "Gadsden",
    state: "AL",
    founded: 1925,
    control: "public",
    yardLabel: "Gadsden State Community Yard",
  },
  {
    id: "grambling",
    school: "Grambling State University",
    shortName: "Grambling State",
    city: "Grambling",
    state: "LA",
    founded: 1901,
    control: "public",
    yardLabel: "Grambling State Yard",
  },
  {
    id: "hampton",
    school: "Hampton University",
    shortName: "Hampton",
    city: "Hampton",
    state: "VA",
    founded: 1868,
    control: "private",
    yardLabel: "Hampton Yard",
  },
  {
    id: "harris-stowe-st",
    school: "Harris-Stowe State University",
    shortName: "Harris-Stowe",
    city: "St. Louis",
    state: "MO",
    founded: 1857,
    control: "public",
    yardLabel: "Harris-Stowe Yard",
  },
  {
    id: "hinds-cc-at-utica",
    school: "Hinds Community College at Utica",
    shortName: "Hinds Utica",
    city: "Utica",
    state: "MS",
    founded: 1903,
    control: "public",
    yardLabel: "Hinds Utica Yard",
  },
  {
    id: "howard",
    school: "Howard University",
    shortName: "Howard",
    city: "Washington",
    state: "DC",
    founded: 1867,
    control: "private",
    yardLabel: "Howard Yard",
  },
  {
    id: "huston-tillotson",
    school: "Huston-Tillotson University",
    shortName: "Huston-Tillotson",
    city: "Austin",
    state: "TX",
    founded: 1875,
    control: "private",
    yardLabel: "Huston-Tillotson Yard",
  },
  {
    id: "interdenominational-theological-",
    school: "Interdenominational Theological Center",
    shortName: "ITC",
    city: "Atlanta",
    state: "GA",
    founded: 1958,
    control: "private",
    yardLabel: "ITC Yard",
  },
  {
    id: "j-f-drake-st-ctc",
    school: "J. F. Drake State Community and Technical College",
    shortName: "Drake State",
    city: "Huntsville",
    state: "AL",
    founded: 1961,
    control: "public",
    yardLabel: "Drake State Yard",
  },
  {
    id: "jsu",
    school: "Jackson State University",
    shortName: "JSU",
    city: "Jackson",
    state: "MS",
    founded: 1877,
    control: "public",
    yardLabel: "JSU Yard",
  },
  {
    id: "jarvis-christian",
    school: "Jarvis Christian University",
    shortName: "Jarvis Christian",
    city: "Hawkins",
    state: "TX",
    founded: 1912,
    control: "private",
    yardLabel: "Jarvis Christian Yard",
  },
  {
    id: "johnson-c-smith",
    school: "Johnson C. Smith University",
    shortName: "Johnson C. Smith",
    city: "Charlotte",
    state: "NC",
    founded: 1867,
    control: "private",
    yardLabel: "Johnson C. Smith Yard",
  },
  {
    id: "kentucky-st",
    school: "Kentucky State University",
    shortName: "Kentucky State",
    city: "Frankfort",
    state: "KY",
    founded: 1886,
    control: "public",
    yardLabel: "Kentucky State Yard",
  },
  {
    id: "knoxville",
    school: "Knoxville College",
    shortName: "Knoxville",
    city: "Knoxville",
    state: "TN",
    founded: 1875,
    control: "private",
    yardLabel: "Knoxville Yard",
  },
  {
    id: "lane",
    school: "Lane College",
    shortName: "Lane",
    city: "Jackson",
    state: "TN",
    founded: 1882,
    control: "private",
    yardLabel: "Lane Yard",
  },
  {
    id: "langston",
    school: "Langston University",
    shortName: "Langston",
    city: "Langston",
    state: "OK",
    founded: 1897,
    control: "public",
    yardLabel: "Langston Yard",
  },
  {
    id: "lawson-st-cc",
    school: "Lawson State Community College",
    shortName: "Lawson State Community",
    city: "Birmingham",
    state: "AL",
    founded: 1949,
    control: "public",
    yardLabel: "Lawson State Community Yard",
  },
  {
    id: "lemoyne-owen",
    school: "LeMoyne-Owen College",
    shortName: "LeMoyne-Owen",
    city: "Memphis",
    state: "TN",
    founded: 1862,
    control: "private",
    yardLabel: "LeMoyne-Owen Yard",
  },
  {
    id: "lincoln-u-missouri",
    school: "Lincoln University of Missouri",
    shortName: "Lincoln MO",
    city: "Jefferson City",
    state: "MO",
    founded: 1866,
    control: "public",
    yardLabel: "Lincoln MO Yard",
  },
  {
    id: "lincoln-u-pennsylvania",
    school: "Lincoln University of Pennsylvania",
    shortName: "Lincoln PA",
    city: "Lincoln University",
    state: "PA",
    founded: 1854,
    control: "public",
    yardLabel: "Lincoln PA Yard",
  },
  {
    id: "livingstone",
    school: "Livingstone College",
    shortName: "Livingstone",
    city: "Salisbury",
    state: "NC",
    founded: 1879,
    control: "private",
    yardLabel: "Livingstone Yard",
  },
  {
    id: "u-maryland-eastern-shore",
    school: "University of Maryland Eastern Shore",
    shortName: "UMES",
    city: "Princess Anne",
    state: "MD",
    founded: 1886,
    control: "public",
    yardLabel: "UMES Yard",
  },
  {
    id: "meharry",
    school: "Meharry Medical College",
    shortName: "Meharry Medical",
    city: "Nashville",
    state: "TN",
    founded: 1876,
    control: "private",
    yardLabel: "Meharry Medical Yard",
  },
  {
    id: "miles",
    school: "Miles College",
    shortName: "Miles",
    city: "Fairfield",
    state: "AL",
    founded: 1898,
    control: "private",
    yardLabel: "Miles Yard",
  },
  {
    id: "mississippi-valley-st",
    school: "Mississippi Valley State University",
    shortName: "Mississippi Valley State",
    city: "Itta Bena",
    state: "MS",
    founded: 1950,
    control: "public",
    yardLabel: "Mississippi Valley State Yard",
  },
  {
    id: "morehouse",
    school: "Morehouse College",
    shortName: "Morehouse",
    city: "Atlanta",
    state: "GA",
    founded: 1867,
    control: "private",
    yardLabel: "Morehouse Yard",
  },
  {
    id: "morehouse-school-of-medicine",
    school: "Morehouse School of Medicine",
    shortName: "MSM",
    city: "Atlanta",
    state: "GA",
    founded: 1975,
    control: "private",
    yardLabel: "MSM Yard",
  },
  {
    id: "morgan",
    school: "Morgan State University",
    shortName: "Morgan State",
    city: "Baltimore",
    state: "MD",
    founded: 1867,
    control: "public",
    yardLabel: "Morgan State Yard",
  },
  {
    id: "morris-brown",
    school: "Morris Brown College",
    shortName: "Morris Brown",
    city: "Atlanta",
    state: "GA",
    founded: 1881,
    control: "private",
    yardLabel: "Morris Brown Yard",
  },
  {
    id: "morris",
    school: "Morris College",
    shortName: "Morris",
    city: "Sumter",
    state: "SC",
    founded: 1908,
    control: "private",
    yardLabel: "Morris Yard",
  },
  {
    id: "nsu",
    school: "Norfolk State University",
    shortName: "Norfolk State",
    city: "Norfolk",
    state: "VA",
    founded: 1935,
    control: "public",
    yardLabel: "Norfolk State Yard",
  },
  {
    id: "ncat",
    school: "North Carolina A&T State University",
    shortName: "NC A&T",
    city: "Greensboro",
    state: "NC",
    founded: 1891,
    control: "public",
    yardLabel: "NC A&T Yard",
  },
  {
    id: "north-carolina-central",
    school: "North Carolina Central University",
    shortName: "North Carolina Central",
    city: "Durham",
    state: "NC",
    founded: 1910,
    control: "public",
    yardLabel: "North Carolina Central Yard",
  },
  {
    id: "oakwood",
    school: "Oakwood University",
    shortName: "Oakwood",
    city: "Huntsville",
    state: "AL",
    founded: 1896,
    control: "private",
    yardLabel: "Oakwood Yard",
  },
  {
    id: "paine",
    school: "Paine College",
    shortName: "Paine",
    city: "Augusta",
    state: "GA",
    founded: 1882,
    control: "private",
    yardLabel: "Paine Yard",
  },
  {
    id: "paul-quinn",
    school: "Paul Quinn College",
    shortName: "Paul Quinn",
    city: "Dallas",
    state: "TX",
    founded: 1872,
    control: "private",
    yardLabel: "Paul Quinn Yard",
  },
  {
    id: "payne-theological-seminary",
    school: "Payne Theological Seminary",
    shortName: "Payne Theological",
    city: "Wilberforce",
    state: "OH",
    founded: 1856,
    control: "private",
    yardLabel: "Payne Theological Yard",
  },
  {
    id: "philander-smith",
    school: "Philander Smith University",
    shortName: "Philander Smith",
    city: "Little Rock",
    state: "AR",
    founded: 1877,
    control: "private",
    yardLabel: "Philander Smith Yard",
  },
  {
    id: "pvamu",
    school: "Prairie View A&M University",
    shortName: "PVAMU",
    city: "Prairie View",
    state: "TX",
    founded: 1876,
    control: "public",
    yardLabel: "PVAMU Yard",
  },
  {
    id: "rust",
    school: "Rust College",
    shortName: "Rust",
    city: "Holly Springs",
    state: "MS",
    founded: 1866,
    control: "private",
    yardLabel: "Rust Yard",
  },
  {
    id: "savannah-st",
    school: "Savannah State University",
    shortName: "Savannah State",
    city: "Savannah",
    state: "GA",
    founded: 1890,
    control: "public",
    yardLabel: "Savannah State Yard",
  },
  {
    id: "selma",
    school: "Selma University",
    shortName: "Selma",
    city: "Selma",
    state: "AL",
    founded: 1878,
    control: "private",
    yardLabel: "Selma Yard",
  },
  {
    id: "shaw",
    school: "Shaw University",
    shortName: "Shaw",
    city: "Raleigh",
    state: "NC",
    founded: 1865,
    control: "private",
    yardLabel: "Shaw Yard",
  },
  {
    id: "shelton-st-cc",
    school: "Shelton State Community College",
    shortName: "Shelton State Community",
    city: "Tuscaloosa",
    state: "AL",
    founded: 1952,
    control: "public",
    yardLabel: "Shelton State Community Yard",
  },
  {
    id: "simmons-of-kentucky",
    school: "Simmons College of Kentucky",
    shortName: "Simmons KY",
    city: "Louisville",
    state: "KY",
    founded: 1869,
    control: "private",
    yardLabel: "Simmons KY Yard",
  },
  {
    id: "south-carolina-st",
    school: "South Carolina State University",
    shortName: "South Carolina State",
    city: "Orangeburg",
    state: "SC",
    founded: 1896,
    control: "public",
    yardLabel: "South Carolina State Yard",
  },
  {
    id: "southern-at-new-orleans",
    school: "Southern University at New Orleans",
    shortName: "SUNO",
    city: "New Orleans",
    state: "LA",
    founded: 1956,
    control: "public",
    yardLabel: "SUNO Yard",
  },
  {
    id: "southern-at-shreveport",
    school: "Southern University at Shreveport",
    shortName: "SUSLA",
    city: "Shreveport",
    state: "LA",
    founded: 1967,
    control: "public",
    yardLabel: "SUSLA Yard",
  },
  {
    id: "southern",
    school: "Southern University and A&M College",
    shortName: "Southern U",
    city: "Baton Rouge",
    state: "LA",
    founded: 1880,
    control: "public",
    yardLabel: "Southern U Yard",
  },
  {
    id: "southwestern-christian",
    school: "Southwestern Christian College",
    shortName: "Southwestern Christian",
    city: "Terrell",
    state: "TX",
    founded: 1948,
    control: "private",
    yardLabel: "Southwestern Christian Yard",
  },
  {
    id: "spelman",
    school: "Spelman College",
    shortName: "Spelman",
    city: "Atlanta",
    state: "GA",
    founded: 1881,
    control: "private",
    yardLabel: "Spelman Yard",
  },
  {
    id: "st-augustine-s",
    school: "St. Augustine's University",
    shortName: "St. Aug's",
    city: "Raleigh",
    state: "NC",
    founded: 1867,
    control: "private",
    yardLabel: "St. Aug's Yard",
  },
  {
    id: "stillman",
    school: "Stillman College",
    shortName: "Stillman",
    city: "Tuscaloosa",
    state: "AL",
    founded: 1876,
    control: "private",
    yardLabel: "Stillman Yard",
  },
  {
    id: "talladega",
    school: "Talladega College",
    shortName: "Talladega",
    city: "Talladega",
    state: "AL",
    founded: 1867,
    control: "private",
    yardLabel: "Talladega Yard",
  },
  {
    id: "tsu",
    school: "Tennessee State University",
    shortName: "TSU",
    city: "Nashville",
    state: "TN",
    founded: 1912,
    control: "public",
    yardLabel: "TSU Yard",
  },
  {
    id: "texas",
    school: "Texas College",
    shortName: "Texas",
    city: "Tyler",
    state: "TX",
    founded: 1894,
    control: "private",
    yardLabel: "Texas Yard",
  },
  {
    id: "txsu",
    school: "Texas Southern University",
    shortName: "TSU Houston",
    city: "Houston",
    state: "TX",
    founded: 1927,
    control: "public",
    yardLabel: "TSU Houston Yard",
  },
  {
    id: "tougaloo",
    school: "Tougaloo College",
    shortName: "Tougaloo",
    city: "Tougaloo",
    state: "MS",
    founded: 1869,
    control: "private",
    yardLabel: "Tougaloo Yard",
  },
  {
    id: "trenholm-st-cc",
    school: "Trenholm State Community College",
    shortName: "Trenholm State Community",
    city: "Montgomery",
    state: "AL",
    founded: 1947,
    control: "public",
    yardLabel: "Trenholm State Community Yard",
  },
  {
    id: "tuskegee",
    school: "Tuskegee University",
    shortName: "Tuskegee",
    city: "Tuskegee",
    state: "AL",
    founded: 1881,
    control: "private",
    yardLabel: "Tuskegee Yard",
  },
  {
    id: "u-virgin-islands",
    school: "University of the Virgin Islands",
    shortName: "UVI",
    city: "St. Thomas",
    state: "VI",
    founded: 1962,
    control: "public",
    yardLabel: "UVI Yard",
  },
  {
    id: "vsu",
    school: "Virginia State University",
    shortName: "Virginia State",
    city: "Petersburg",
    state: "VA",
    founded: 1882,
    control: "public",
    yardLabel: "Virginia State Yard",
  },
  {
    id: "virginia-union",
    school: "Virginia Union University",
    shortName: "Virginia Union",
    city: "Richmond",
    state: "VA",
    founded: 1865,
    control: "private",
    yardLabel: "Virginia Union Yard",
  },
  {
    id: "virginia-u-lynchburg",
    school: "Virginia University of Lynchburg",
    shortName: "VU Lynchburg",
    city: "Lynchburg",
    state: "VA",
    founded: 1886,
    control: "private",
    yardLabel: "VU Lynchburg Yard",
  },
  {
    id: "voorhees",
    school: "Voorhees University",
    shortName: "Voorhees",
    city: "Denmark",
    state: "SC",
    founded: 1897,
    control: "private",
    yardLabel: "Voorhees Yard",
  },
  {
    id: "west-virginia-st",
    school: "West Virginia State University",
    shortName: "West Virginia State",
    city: "Institute",
    state: "WV",
    founded: 1891,
    control: "public",
    yardLabel: "West Virginia State Yard",
  },
  {
    id: "wilberforce",
    school: "Wilberforce University",
    shortName: "Wilberforce",
    city: "Wilberforce",
    state: "OH",
    founded: 1856,
    control: "private",
    yardLabel: "Wilberforce Yard",
  },
  {
    id: "wiley",
    school: "Wiley University",
    shortName: "Wiley",
    city: "Marshall",
    state: "TX",
    founded: 1873,
    control: "private",
    yardLabel: "Wiley Yard",
  },
  {
    id: "winston-salem-st",
    school: "Winston-Salem State University",
    shortName: "Winston-Salem State",
    city: "Winston-Salem",
    state: "NC",
    founded: 1892,
    control: "public",
    yardLabel: "Winston-Salem State Yard",
  },
  {
    id: "xavier",
    school: "Xavier University of Louisiana",
    shortName: "Xavier LA",
    city: "New Orleans",
    state: "LA",
    founded: 1915,
    control: "private",
    yardLabel: "Xavier LA Yard",
  },
];

/** SEC + named NCAA yards — same picker, same table as every HBCU. */
export const NCAA_CROSSOVER_CATALOG: HbcuInstitution[] = [
  {
    id: "vanderbilt",
    school: "Vanderbilt University",
    shortName: "Vanderbilt",
    city: "Nashville",
    state: "TN",
    founded: 1873,
    control: "private",
    yardLabel: "Vanderbilt Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "belmont",
    school: "Belmont University",
    shortName: "Belmont",
    city: "Nashville",
    state: "TN",
    founded: 1890,
    control: "private",
    yardLabel: "Belmont Yard",
    kind: "ncaa",
    conference: "MVC",
  },
  {
    id: "tennessee",
    school: "University of Tennessee",
    shortName: "Tennessee",
    city: "Knoxville",
    state: "TN",
    founded: 1794,
    control: "public",
    yardLabel: "Tennessee Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "ut-austin",
    school: "University of Texas at Austin",
    shortName: "Texas",
    city: "Austin",
    state: "TX",
    founded: 1883,
    control: "public",
    yardLabel: "Texas Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "alabama",
    school: "University of Alabama",
    shortName: "Alabama",
    city: "Tuscaloosa",
    state: "AL",
    founded: 1831,
    control: "public",
    yardLabel: "Alabama Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "auburn",
    school: "Auburn University",
    shortName: "Auburn",
    city: "Auburn",
    state: "AL",
    founded: 1856,
    control: "public",
    yardLabel: "Auburn Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "florida",
    school: "University of Florida",
    shortName: "Florida",
    city: "Gainesville",
    state: "FL",
    founded: 1853,
    control: "public",
    yardLabel: "Florida Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "georgia",
    school: "University of Georgia",
    shortName: "Georgia",
    city: "Athens",
    state: "GA",
    founded: 1785,
    control: "public",
    yardLabel: "Georgia Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "kentucky",
    school: "University of Kentucky",
    shortName: "Kentucky",
    city: "Lexington",
    state: "KY",
    founded: 1865,
    control: "public",
    yardLabel: "Kentucky Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "lsu",
    school: "Louisiana State University",
    shortName: "LSU",
    city: "Baton Rouge",
    state: "LA",
    founded: 1860,
    control: "public",
    yardLabel: "LSU Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "ole-miss",
    school: "University of Mississippi",
    shortName: "Ole Miss",
    city: "Oxford",
    state: "MS",
    founded: 1848,
    control: "public",
    yardLabel: "Ole Miss Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "miss-st",
    school: "Mississippi State University",
    shortName: "Mississippi State",
    city: "Starkville",
    state: "MS",
    founded: 1878,
    control: "public",
    yardLabel: "Mississippi State Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "missouri",
    school: "University of Missouri",
    shortName: "Missouri",
    city: "Columbia",
    state: "MO",
    founded: 1839,
    control: "public",
    yardLabel: "Missouri Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "south-carolina",
    school: "University of South Carolina",
    shortName: "South Carolina",
    city: "Columbia",
    state: "SC",
    founded: 1801,
    control: "public",
    yardLabel: "South Carolina Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "arkansas",
    school: "University of Arkansas",
    shortName: "Arkansas",
    city: "Fayetteville",
    state: "AR",
    founded: 1871,
    control: "public",
    yardLabel: "Arkansas Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "texas-am",
    school: "Texas A&M University",
    shortName: "Texas A&M",
    city: "College Station",
    state: "TX",
    founded: 1876,
    control: "public",
    yardLabel: "Texas A&M Yard",
    kind: "ncaa",
    conference: "SEC",
  },
  {
    id: "oklahoma",
    school: "University of Oklahoma",
    shortName: "Oklahoma",
    city: "Norman",
    state: "OK",
    founded: 1890,
    control: "public",
    yardLabel: "Oklahoma Yard",
    kind: "ncaa",
    conference: "SEC",
  },
];

export function yardKind(h: HbcuInstitution): YardKind {
  return h.kind ?? "hbcu";
}

/** Every pickable yard — HBCU catalog + NCAA/SEC crossover. */
export const ALL_YARD_CATALOG: HbcuInstitution[] = [
  ...HBCU_CATALOG,
  ...NCAA_CROSSOVER_CATALOG,
];

export const HBCU_BY_ID: Record<string, HbcuInstitution> = Object.fromEntries(
  ALL_YARD_CATALOG.map((h) => [h.id, h]),
);

export const HBCU_STATES = Array.from(
  new Set(ALL_YARD_CATALOG.map((h) => h.state)),
).sort();

export function getHbcu(id: string): HbcuInstitution | null {
  return HBCU_BY_ID[id] ?? null;
}

export function searchHbcus(
  query: string,
  opts?: { state?: string; control?: HbcuControl | "all" },
): HbcuInstitution[] {
  const q = query.trim().toLowerCase();
  const state = opts?.state && opts.state !== "all" ? opts.state : null;
  const control = opts?.control && opts.control !== "all" ? opts.control : null;
  return ALL_YARD_CATALOG.filter((h) => {
    if (state && h.state !== state) return false;
    if (control && h.control !== control) return false;
    if (!q) return true;
    return (
      h.school.toLowerCase().includes(q) ||
      h.shortName.toLowerCase().includes(q) ||
      h.city.toLowerCase().includes(q) ||
      h.state.toLowerCase().includes(q) ||
      h.id.includes(q) ||
      h.yardLabel.toLowerCase().includes(q) ||
      (h.conference?.toLowerCase().includes(q) ?? false)
    );
  });
}

export function hbcuLocation(h: HbcuInstitution): string {
  return `${h.city}, ${h.state}`;
}

export function catalogStats(): {
  total: number;
  public: number;
  private: number;
} {
  const publicN = ALL_YARD_CATALOG.filter((h) => h.control === "public").length;
  return {
    total: ALL_YARD_CATALOG.length,
    public: publicN,
    private: ALL_YARD_CATALOG.length - publicN,
  };
}
